name: blue
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py39h06a4308_0
  - archspec=0.2.1=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boltons=23.0.0=py39h06a4308_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py39h06a4308_0
  - conda=24.1.0=py39h06a4308_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py39h06a4308_0
  - conda-package-streaming=0.9.0=py39h06a4308_0
  - cryptography=41.0.2=py39h22a60cf_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.8.0=py39h06a4308_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py39h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py39h2f386ee_0
  - ipython=8.12.2=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - jupyter_events=0.6.3=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyter_server_terminals=0.4.4=py39h06a4308_1
  - jupyterlab_pygments=0.1.2=py_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.6=haf1ee3a_0
  - libmambapy=1.5.6=py39h2dafd23_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=11.9.0.86=0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxml2=2.10.4=hf1b16e4_1
  - libxslt=1.1.37=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lxml=4.9.2=py39h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - menuinst=2.0.2=py39h06a4308_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - nb_conda_kernels=2.3.1=py39h06a4308_0
  - nbclassic=0.5.5=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - notebook=6.5.3=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-json-logger=2.0.7=py39h06a4308_0
  - pytorch=2.2.0=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py39h5eee18b_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py39h06a4308_0
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.4=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py39h06a4308_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - torchtriton=2.2.0=py39
  - tornado=6.3.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - blessings==1.7
      - chardet==5.2.0
      - click==8.1.7
      - colorama==0.4.6
      - dataproperty==1.0.1
      - datasets==2.16.1
      - dill==0.3.7
      - evaluate==0.4.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gpustat==0.6.0
      - huggingface-hub==0.20.3
      - joblib==1.3.2
      - jsonlines==4.0.0
      - lm-dataformat==0.0.20
      - lm-eval==0.4.1
      - mbstrdecoder==1.1.3
      - multidict==6.0.5
      - multiprocess==0.70.15
      - networkx==3.2.1
      - nltk==3.8.1
      - numexpr==2.9.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.0
      - pathvalidate==3.2.0
      - peft==0.8.2
      - portalocker==2.8.2
      - psutil==5.9.1
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.11.1
      - pytablewriter==1.2.0
      - pytz==2024.1
      - regex==2023.12.25
      - responses==0.18.0
      - rouge-score==0.1.2
      - sacrebleu==2.4.0
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - sqlitedict==2.1.0
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.4
      - threadpoolctl==3.2.0
      - tokenizers==0.15.1
      - torch==2.2.0
      - tqdm==4.66.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.37.2
      - triton==2.2.0
      - typepy==1.3.2
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - ujson==5.9.0
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: /egr/research-optml/chongyu/anaconda3/envs/blue